class Iyi::Program
  # Temporary files which are generated by macro runs that need to be
  # deleted after the compilation is finished.
  getter tempfiles = [] of String

  # Returns a `MacroExpander` to expand macro code into crystal code.
  getter(macro_expander) { MacroExpander.new self }

  # A cache of compiled "macro run" files.
  # The keys are filenames that were compiled, the values are executable
  # filenames ready to be run (so they don't need to be compiled twice),
  # together with the time it took to compile them and whether a previous
  # compilation was reused.
  # The elapsed time is only needed for stats.
  record CompiledMacroRun, filename : String, elapsed : Time::Span, reused : Bool
  property compiled_macros_cache = {} of String => CompiledMacroRun

  property interpreted_node_hook : Proc(ASTNode, Bool, Bool, Location?, Nil)? = nil
  property macro_expanded_hook : Proc(Nil)? = nil
  property macro_expansion_error_hook : Proc(::Exception?, Nil)? = nil

  def expand_macro(a_macro : Macro, call : Call, scope : Type, path_lookup : Type? = nil, a_def : Def? = nil)
    check_call_to_deprecated_macro a_macro, call

    interpreter = MacroInterpreter.new self, scope, path_lookup || scope, a_macro, call, a_def, in_macro: true
    Prof.span("  macro: interpret") { a_macro.body.accept interpreter }
    {Prof.span("  macro: to_s (stringify)") { interpreter.to_s }, interpreter.macro_expansion_pragmas}
  rescue ex
    raise ex if @program.macro_expansion_error_hook.nil?

    # See SkipMacroCodeCoverageException's definition for more information.
    raise SkipMacroCodeCoverageException.new ex
  ensure
    @program.macro_expanded_hook.try &.call
  end

  def expand_macro(node : ASTNode, scope : Type, path_lookup : Type? = nil, free_vars = nil, a_def : Def? = nil)
    interpreter = MacroInterpreter.new self, scope, path_lookup || scope, node.location, def: a_def, in_macro: false
    interpreter.free_vars = free_vars
    Prof.span("  macro: interpret") { node.accept interpreter }
    {Prof.span("  macro: to_s (stringify)") { interpreter.to_s }, interpreter.macro_expansion_pragmas}
  rescue ex
    raise ex if @program.macro_expansion_error_hook.nil?

    # See SkipMacroCodeCoverageException's definition for more information.
    raise SkipMacroCodeCoverageException.new ex
  ensure
    @program.macro_expanded_hook.try &.call
  end

  def parse_macro_source(generated_source, macro_expansion_pragmas, the_macro, node, vars, current_def = nil, inside_type = false, inside_exp = false, mode : Parser::ParseMode = :normal, visibility : Visibility = :public)
    parse_macro_source generated_source, macro_expansion_pragmas, the_macro, node, vars, current_def, inside_type, inside_exp, visibility, &.parse(mode)
  end

  def parse_macro_source(generated_source, macro_expansion_pragmas, the_macro, node, vars, current_def = nil, inside_type = false, inside_exp = false, visibility : Visibility = :public, &)
    # iyi: an expansion is read back as source, and the lexer raises for a
    # byte that is not UTF-8 - which every parse of a file turns into a
    # sentence, and nothing here did: `puts {{ "\xff".id }}` ended `check` in
    # "Unexpected byte 0xff at position 0, malformed UTF-8
    # (InvalidByteSequenceError)" and a stack trace. Refused at the call.
    unless generated_source.valid_encoding?
      node.raise "macro expansion is not UTF-8 text: it holds a byte that is no character (a \"\\xff\" in a string it writes out, say), and an expansion is read back as source"
    end
    parser = @program.new_parser(generated_source, var_scopes: [vars.dup])
    virtual = VirtualFile.new(the_macro, generated_source, node.location)
    virtual.line_origins = line_origins_of(generated_source, macro_expansion_pragmas)
    parser.filename = virtual
    parser.macro_expansion_pragmas = macro_expansion_pragmas
    parser.visibility = visibility
    parser.def_nest = 1 if current_def && !current_def.is_a?(External)
    parser.fun_nest = 1 if current_def && current_def.is_a?(External)
    parser.type_nest = 1 if inside_type
    parser.wants_doc = @program.wants_doc?
    # iyi: see `VirtualFile#depth`.
    if virtual.depth > VirtualFile::DEPTH_LIMIT
      node.raise "macro expansion nested more than #{VirtualFile::DEPTH_LIMIT} deep: a macro whose expansion runs it again (a call of itself, of a macro that calls it back, or a class that sets off the `inherited` hook that wrote it) has to stop before that"
    end
    generated_node = Prof.span("  macro: reparse") { yield parser }
    Prof.span("  macro: normalize") { normalize(generated_node, inside_exp: inside_exp, current_def: current_def) }
  end

  # iyi: a hook a derive defines (`macro finished`, `inherited`, `included`,
  # `extended`, `method_added`) runs after the derive has returned, against
  # whatever the rest of the program declares, which is the whole-program
  # answer R-5 keeps from a derive (SPEC.md II.4). Refused while the derive
  # expands. A derive's `macro finished` holding an escaped
  # `{{ Base.all_subclasses }}` answered `A,B` beside a `B` declared after
  # the derived struct, past the refusal `all_subclasses` has in a derive.
  def iyi_refuse_hook_in_derive(node : Macro) : Nil
    return unless expanding_derive? && node.name.in?(Iyi::IyiMod::MACRO_HOOKS)

    node.raise "`macro #{node.name}` is not available to a derive: a hook runs " \
               "after the derive, against the whole program, and a derive may only " \
               "read the declaration it is attached to and what that declaration's " \
               "types implement — see SPEC.md II.4"
  end

  # iyi: an inline macro's `LocOriginPragma`s as lines: the expansion's
  # line at each pragma is the origin's, and each line after it the next
  # one, until the next pragma. Read before the parse, which consumes the
  # pragmas.
  private def line_origins_of(source : String, pragmas : Hash(Int32, Array(Lexer::LocPragma))?) : Hash(Int32, Int32)?
    return nil unless pragmas
    starts = [] of {Int32, Int32}
    pragmas.each do |position, list|
      list.each do |pragma|
        starts << {position, pragma.line_number} if pragma.is_a?(Lexer::LocOriginPragma)
      end
    end
    return nil if starts.empty?
    # The expansion's line at each byte where a line starts.
    line_starts = [0]
    source.each_byte.with_index { |byte, index| line_starts << index + 1 if byte == '\n'.ord }
    origins = {} of Int32 => Int32
    starts.each_with_index do |(position, origin), index|
      first = (line_starts.bsearch_index { |start| start > position } || line_starts.size)
      last = if following = starts[index + 1]?
               (line_starts.bsearch_index { |start| start > following[0] } || line_starts.size) - 1
             else
               line_starts.size
             end
      (first..last).each { |line| origins[line] = origin + line - first }
    end
    origins
  end

  record MacroRunResult, stdout : String, stderr : String, status : Process::Status

  # iyi: `run` compiles a program and executes it, so a front end that links no
  # LLVM cannot do it — and says so rather than failing somewhere in the middle
  # of a build it cannot finish (see `../llvm_shim.cr`). II.10 measured this at
  # +7.4 s per distinct script on a cold build; it is not on the path a front
  # end is for.
  {% if flag?(:without_llvm) %}
    def macro_run(filename, args)
      raise Iyi::Error.new("`run` needs a compiler that can generate code, and this one links no LLVM")
    end
  {% else %}

  def macro_run(filename, args)
    compiled_macro_run = @compiled_macros_cache[filename] ||= macro_compile(filename)
    compiled_file = compiled_macro_run.filename

    out_io = IO::Memory.new
    err_io = IO::Memory.new
    Process.run(compiled_file, args: args, output: out_io, error: err_io)
    MacroRunResult.new(out_io.to_s, err_io.to_s, $?)
  end

  record RequireWithTimestamp, filename : String, epoch : Int64 do
    include JSON::Serializable
  end

  def macro_compile(filename)
    time = Time.instant

    source = File.read(filename)

    # We store the executable relative to the cache directory for 'filename',
    # that way if it's already there from a previous compilation, and no file
    # that this program uses changes, we can simply avoid recompiling it again
    #
    # NOTE: it could happen that a macro run program runs macros that could
    # change the program behaviour even if files don't change, but this is
    # discouraged (and we should strongly document it) because it prevents
    # incremental compiles.
    program_dir = CacheDir.instance.directory_for(filename)
    executable_path = File.join(program_dir, "macro_run")
    recorded_requires_path = File.join(program_dir, "recorded_requires")
    requires_path = File.join(program_dir, "requires")

    {% unless flag?(:win32) %}
      # First, update times for the program dir, so it remains in the cache longer
      # (this is specially useful if a macro run program is used by multiple programs)
      now = Time.utc
      File.utime(now, now, program_dir)
    {% end %}

    if can_reuse_previous_compilation?(filename, executable_path, recorded_requires_path, requires_path)
      return CompiledMacroRun.new(executable_path, time.elapsed, true)
    end

    # iyi: linked under this process's own name and renamed into place. The
    # directory is one per helper and shared by every compiler on the
    # machine, and the link went straight to `macro_run`: two `iyi check` of
    # the eiy exercise at once, its helper stale, failed one of the two in
    # each of 4 rounds with "LNK1104: cannot open file ...\macro_run" -
    # Windows will not write over a program that is running, and the other
    # compiler was running it. A rename is whole, so whoever starts the
    # program starts the old one or the new one, never half of one. Windows
    # refuses that rename too while the old one runs; then this process
    # keeps its own copy until it exits, and records nothing, since the
    # requires below would vouch for a `macro_run` that is still the old
    # program.
    staging_path = "#{executable_path}.#{Process.pid}"
    sweep_macro_run_leftovers(program_dir, executable_path)
    result = host_compiler.compile Compiler::Source.new(filename, source), staging_path
    begin
      File.rename(staging_path, executable_path)
    rescue File::Error
      at_exit { File.delete?(staging_path) rescue nil }
      return CompiledMacroRun.new(staging_path, time.elapsed, false)
    end

    # Write the new files from which 'filename' depends into the cache dir
    # (here we store how to obtain these files, because a require might use
    # '/*' or '/**' and we need to recompile if a file is added or removed)
    File.open(recorded_requires_path, "w") do |file|
      result.program.recorded_requires.to_json(file)
    end

    # Together with their timestamp
    # (this is the list of all effective files that were required)
    requires_with_timestamps = result.program.requires.map do |required_file|
      epoch = File.info(required_file).modification_time.to_unix
      RequireWithTimestamp.new(required_file, epoch)
    end

    File.open(requires_path, "w") do |file|
      requires_with_timestamps.to_json(file)
    end

    CompiledMacroRun.new(executable_path, time.elapsed, false)
  end

  # The copies `macro_compile` kept and a killed compiler left, an hour
  # after: a younger one may be one another compiler has just linked and not
  # yet started, and a copy that is running refuses the delete anyway.
  private def sweep_macro_run_leftovers(program_dir, executable_path) : Nil
    prefix = "#{File.basename(executable_path)}."
    cutoff = Time.utc - 1.hour
    Dir.each_child(program_dir) do |name|
      next unless name.starts_with?(prefix)
      path = File.join(program_dir, name)
      next unless (info = File.info?(path)) && info.modification_time < cutoff
      File.delete?(path) rescue nil
    end
  rescue File::Error
  end

  @host_compiler : Compiler?

  # Creates a compiler instance with the host as target used for macro_run
  # compilation.
  def host_compiler
    @host_compiler ||= Compiler.new.tap do |host_compiler|
      if compiler = self.compiler
        # When cross-compiling, the host compiler shouldn't copy the config for
        # the target compiler and use the system defaults instead.
        # TODO: Add configuration overrides for host compiler to CLI.
        unless compiler.cross_compile?
          host_compiler.flags = compiler.flags
          host_compiler.dump_ll = compiler.dump_ll?
          host_compiler.link_flags = compiler.link_flags
          host_compiler.mcpu = compiler.mcpu
          host_compiler.mattr = compiler.mattr
          host_compiler.mcmodel = compiler.mcmodel
          host_compiler.single_module = compiler.single_module?
          host_compiler.static = compiler.static?
        end

        # Copy default settings that are not specific to host and target context:
        host_compiler.n_threads = compiler.n_threads
        host_compiler.prelude = compiler.prelude
      end

      # Although release takes longer, once the bc is cached in .crystal
      # the subsequent times will make program execution faster.
      host_compiler.release!

      # Don't cleanup old directories after compiling: it might happen
      # that in doing so we remove the directory associated with the current
      # compilation (for example if we have more than 10 macro runs, the current
      # directory will be the oldest).
      host_compiler.cleanup = false

      # No need to generate debug info for macro run programs
      host_compiler.debug = Iyi::Debug::None
    end
  end

  {% end %}

  private def can_reuse_previous_compilation?(filename, executable_path, recorded_requires_path, requires_path)
    return false unless File.exists?(executable_path)
    return false unless File.exists?(recorded_requires_path)
    return false unless File.exists?(requires_path)

    recorded_requires =
      begin
        Array(Program::RecordedRequire).from_json(File.read(recorded_requires_path))
      rescue JSON::Error
        return false
      end

    requires_with_timestamps =
      begin
        Array(RequireWithTimestamp).from_json(File.read(requires_path))
      rescue JSON::Error
        return false
      end

    # From the recorded requires we reconstruct the effective required files.
    # We start with the target filename
    required_files = Set{filename}
    recorded_requires.map do |recorded_require|
      files = @program.find_in_path(recorded_require.filename, recorded_require.relative_to)
      required_files.concat(files) if files
    rescue Iyi::IyiPath::NotFoundError
      # Maybe the file is gone
      next
    end

    new_requires_with_timestamps = required_files.map do |required_file|
      epoch = File.info(required_file).modification_time.to_unix
      RequireWithTimestamp.new(required_file, epoch)
    end

    # Quick check: if there are a different number of files, something changed
    if requires_with_timestamps.size != new_requires_with_timestamps.size
      return false
    end

    # Sort both requires and check if they are the same
    requires_with_timestamps.sort_by! &.filename
    new_requires_with_timestamps.sort_by! &.filename
    requires_with_timestamps == new_requires_with_timestamps
  end
end
